In [6]:
from asset_modeling.credit import standard_loan, amortizing_loan, bullet_loan, private_credit_loan_model, loan_portfolio
import pandas as pd

In [3]:
cash_flows = standard_loan(
    par_value=1000,
    coupon_rate=0.05,
    maturity_years=10,
    periodicity="quarterly",
    start_date="2024-03-31",
)

cash_flows

    payment_number periodicity  ... principal_payment  total_payment
0                1   quarterly  ...               0.0           12.5
1                2   quarterly  ...               0.0           12.5
2                3   quarterly  ...               0.0           12.5
3                4   quarterly  ...               0.0           12.5
4                5   quarterly  ...               0.0           12.5
5                6   quarterly  ...               0.0           12.5
6                7   quarterly  ...               0.0           12.5
7                8   quarterly  ...               0.0           12.5
8                9   quarterly  ...               0.0           12.5
9               10   quarterly  ...               0.0           12.5
10              11   quarterly  ...               0.0           12.5
11              12   quarterly  ...               0.0           12.5
12              13   quarterly  ...               0.0           12.5
13              14   quarterly  ...               0.0           12.5
14              15   quarterly  ...               0.0           12.5
15              16   quarterly  ...               0.0           12.5
16              17   quarterly  ...               0.0           12.5
17              18   quarterly  ...               0.0           12.5
18              19   quarterly  ...               0.0           12.5
19              20   quarterly  ...               0.0           12.5
20              21   quarterly  ...               0.0           12.5
21              22   quarterly  ...               0.0           12.5
22              23   quarterly  ...               0.0           12.5
23              24   quarterly  ...               0.0           12.5
24              25   quarterly  ...               0.0           12.5
25              26   quarterly  ...               0.0           12.5
26              27   quarterly  ...               0.0           12.5
27              28   quarterly  ...               0.0           12.5
28              29   quarterly  ...               0.0           12.5
29              30   quarterly  ...               0.0           12.5
30              31   quarterly  ...               0.0           12.5
31              32   quarterly  ...               0.0           12.5
32              33   quarterly  ...               0.0           12.5
33              34   quarterly  ...               0.0           12.5
34              35   quarterly  ...               0.0           12.5
35              36   quarterly  ...               0.0           12.5
36              37   quarterly  ...               0.0           12.5
37              38   quarterly  ...               0.0           12.5
38              39   quarterly  ...               0.0           12.5
39              40   quarterly  ...            1000.0         1012.5

[40 rows x 7 columns]

In [4]:
loan_df = amortizing_loan(
    principal=1000,
    annual_rate=0.05,
    maturity_years=10,
    periodicity="quarterly",
    start_date="2024-03-31",
)

loan_df

,payment_number,periodicity,payment_date,years_elapsed,beginning_balance,scheduled_payment,interest_payment,principal_payment,ending_balance
0,1,quarterly,2024-06-30,0.25,1000.00,31.92,12.50,19.42,980.58
1,2,quarterly,2024-09-30,0.50,980.58,31.92,12.26,19.66,960.91
2,3,quarterly,2024-12-31,0.75,960.91,31.92,12.01,19.91,941.00
3,4,quarterly,2025-03-31,1.00,941.00,31.92,11.76,20.16,920.85
4,5,quarterly,2025-06-30,1.25,920.85,31.92,11.51,20.41,900.43
5,6,quarterly,2025-09-30,1.50,900.43,31.92,11.26,20.67,879.77
6,7,quarterly,2025-12-31,1.75,879.77,31.92,11.00,20.92,858.84
7,8,quarterly,2026-03-31,2.00,858.84,31.92,10.74,21.19,837.66
8,9,quarterly,2026-06-30,2.25,837.66,31.92,10.47,21.45,816.21
9,10,quarterly,2026-09-30,2.50,816.21,31.92,10.20,21.72,794.49
10,11,quarterly,2026-12-31,2.75,794.49,31.92,9.93,21.99,772.50
11,12,quarterly,2027-03-31,3.00,772.50,31.92,9.66,22.27,750.23
12,13,quarterly,2027-06-30,3.25,750.23,31.92,9.38,22.54,727.69
13,14,quarterly,2027-09-30,3.50,727.69,31.92,9.10,22.83,704.86
14,15,quarterly,2027-12-31,3.75,704.86,31.92,8.81,23.11,681.75
15,16,quarterly,2028-03-31,4.00,681.75,31.92,8.52,23.40,658.35
16,17,quarterly,2028-06-30,4.25,658.35,31.92,8.23,23.69,634.66
17,18,quarterly,2028-09-30,4.50,634.66,31.92,7.93,23.99,610.67
18,19,quarterly,2028-12-31,4.75,610.67,31.92,7.63,24.29,586.39
19,20,quarterly,2029-03-31,5.00,586.39,31.92,7.33,24.59,561.80
20,21,quarterly,2029-06-30,5.25,561.80,31.92,7.02,24.90,536.90
21,22,quarterly,2029-09-30,5.50,536.90,31.92,6.71,25.21,511.69
22,23,quarterly,2029-12-31,5.75,511.69,31.92,6.40,25.53,486.16
23,24,quarterly,2030-03-31,6.00,486.16,31.92,6.08,25.84,460.32
24,25,quarterly,2030-06-30,6.25,460.32,31.92,5.75,26.17,434.15
25,26,quarterly,2030-09-30,6.50,434.15,31.92,5.43,26.49,407.65
26,27,quarterly,2030-12-31,6.75,407.65,31.92,5.10,26.83,380.83
27,28,quarterly,2031-03-31,7.00,380.83,31.92,4.76,27.16,353.67
28,29,quarterly,2031-06-30,7.25,353.67,31.92,4.42,27.50,326.17
29,30,quarterly,2031-09-30,7.50,326.17,31.92,4.08,27.84,298.32
30,31,quarterly,2031-12-31,7.75,298.32,31.92,3.73,28.19,270.13
31,32,quarterly,2032-03-31,8.00,270.13,31.92,3.38,28.54,241.59
32,33,quarterly,2032-06-30,8.25,241.59,31.92,3.02,28.90,212.68
33,34,quarterly,2032-09-30,8.50,212.68,31.92,2.66,29.26,183.42
34,35,quarterly,2032-12-31,8.75,183.42,31.92,2.29,29.63,153.79
35,36,quarterly,2033-03-31,9.00,153.79,31.92,1.92,30.00,123.79
36,37,quarterly,2033-06-30,9.25,123.79,31.92,1.55,30.37,93.42
37,38,quarterly,2033-09-30,9.50,93.42,31.92,1.17,30.75,62.67
38,39,quarterly,2033-12-31,9.75,62.67,31.92,0.78,31.14,31.53
39,40,quarterly,2034-03-31,10.00,31.53,31.92,0.39,31.53,0.00

In [4]:
bullet_df = bullet_loan(
    principal=1000,
    annual_rate=0.05,
    maturity_years=10,
    periodicity="quarterly",
    start_date="2024-03-31",
)
bullet_df

    payment_number periodicity  ... total_payment  ending_balance
0                1   quarterly  ...          12.5          1000.0
1                2   quarterly  ...          12.5          1000.0
2                3   quarterly  ...          12.5          1000.0
3                4   quarterly  ...          12.5          1000.0
4                5   quarterly  ...          12.5          1000.0
5                6   quarterly  ...          12.5          1000.0
6                7   quarterly  ...          12.5          1000.0
7                8   quarterly  ...          12.5          1000.0
8                9   quarterly  ...          12.5          1000.0
9               10   quarterly  ...          12.5          1000.0
10              11   quarterly  ...          12.5          1000.0
11              12   quarterly  ...          12.5          1000.0
12              13   quarterly  ...          12.5          1000.0
13              14   quarterly  ...          12.5          1000.0
14              15   quarterly  ...          12.5          1000.0
15              16   quarterly  ...          12.5          1000.0
16              17   quarterly  ...          12.5          1000.0
17              18   quarterly  ...          12.5          1000.0
18              19   quarterly  ...          12.5          1000.0
19              20   quarterly  ...          12.5          1000.0
20              21   quarterly  ...          12.5          1000.0
21              22   quarterly  ...          12.5          1000.0
22              23   quarterly  ...          12.5          1000.0
23              24   quarterly  ...          12.5          1000.0
24              25   quarterly  ...          12.5          1000.0
25              26   quarterly  ...          12.5          1000.0
26              27   quarterly  ...          12.5          1000.0
27              28   quarterly  ...          12.5          1000.0
28              29   quarterly  ...          12.5          1000.0
29              30   quarterly  ...          12.5          1000.0
30              31   quarterly  ...          12.5          1000.0
31              32   quarterly  ...          12.5          1000.0
32              33   quarterly  ...          12.5          1000.0
33              34   quarterly  ...          12.5          1000.0
34              35   quarterly  ...          12.5          1000.0
35              36   quarterly  ...          12.5          1000.0
36              37   quarterly  ...          12.5          1000.0
37              38   quarterly  ...          12.5          1000.0
38              39   quarterly  ...          12.5          1000.0
39              40   quarterly  ...        1012.5             0.0

[40 rows x 9 columns]

In [8]:
schedule_of_investments = pd.DataFrame(
    {
        "investment_name": ["A Corp Term Loan", "B Corp Term Loan",  "C Corp Term Loan",  "D Corp Term Loan",  "E Corp Term Loan"],
        "investment_date": [pd.Timestamp("2020-03-31"), pd.Timestamp("2020-06-30"), pd.Timestamp("2020-09-30"), pd.Timestamp("2020-12-31"), pd.Timestamp("2021-03-31")],
        "maturity_date": [pd.Timestamp("2025-06-30"), pd.Timestamp("2027-06-30"), pd.Timestamp("2026-12-31"), pd.Timestamp("2028-03-31"), pd.Timestamp("2029-06-30")],
        "loan_size": [1_000_000, 1_250_000, 1_000_000, 1_050_000, 1_600_000],
        "spread": [0.07, 0.06, 0.06, 0.08, 0.07],
        "base_rate": ['SOFR', 'SOFR', 'SOFR', 'SOFR', 'SOFR'],
        "sofr_assumption": [0.04, 0.04, 0.04, 0.04, 0.04],
        "cash_interest_rate": [0.08, 0.08, 0.08, 0.08, 0.08],
        "pik_interest": [0.02, 0.02, 0.02, 0.02, 0.02],
        "amortization": [0.01, 0.01, 0.01, 0.01, 0.01],
        "oid": [0.03, 0.02, 0.03, 0.04, 0.02],
        "exit_fee": [0.02, 0.02, 0.02, 0.02, 0.02],
        "prepayment_date": [None, None, None, None, None],
    }
)

portfolio, funds = loan_portfolio(schedule_of_investments)
portfolio

   quarter_end  invested_amount  ...  beginning_balance       irr
0   2020-03-31         970000.0  ...       1.000000e+06      None
1   2020-06-30        2195000.0  ...       2.250000e+06  0.372999
2   2020-09-30        3165000.0  ...       3.252500e+06  0.225195
3   2020-12-31        4173000.0  ...       4.308138e+06  0.193075
4   2021-03-31        5741000.0  ...       5.916303e+06  0.170813
5   2021-06-30        5741000.0  ...       5.927135e+06  0.147625
6   2021-09-30        5741000.0  ...       5.942020e+06  0.136522
7   2021-12-31        5741000.0  ...       5.956980e+06  0.130021
8   2022-03-31        5741000.0  ...       5.972015e+06  0.125753
9   2022-06-30        5741000.0  ...       5.987125e+06  0.122739
10  2022-09-30        5741000.0  ...       6.002311e+06  0.120497
11  2022-12-31        5741000.0  ...       6.017573e+06  0.118765
12  2023-03-31        5741000.0  ...       6.032911e+06  0.117387
13  2023-06-30        5741000.0  ...       6.048325e+06  0.116264
14  2023-09-30        5741000.0  ...       6.063817e+06  0.115333
15  2023-12-31        5741000.0  ...       6.079386e+06  0.114547
16  2024-03-31        5741000.0  ...       6.095033e+06  0.113876
17  2024-06-30        5741000.0  ...       6.110758e+06  0.113297
18  2024-09-30        5741000.0  ...       6.126562e+06  0.112791
19  2024-12-31        5741000.0  ...       6.142444e+06  0.112346
20  2025-03-31        5741000.0  ...       6.158407e+06  0.111952
21  2025-06-30        5741000.0  ...       6.174449e+06  0.112236
22  2025-09-30        4771000.0  ...       5.135361e+06  0.111871
23  2025-12-31        4771000.0  ...       5.148788e+06  0.111613
24  2026-03-31        4771000.0  ...       5.162282e+06  0.111376
25  2026-06-30        4771000.0  ...       5.175843e+06  0.111158
26  2026-09-30        4771000.0  ...       5.189472e+06  0.110957
27  2026-12-31        4771000.0  ...       5.203170e+06  0.111231
28  2027-03-31        3801000.0  ...       4.150538e+06  0.111024
29  2027-06-30        3801000.0  ...       4.161540e+06  0.111415
30  2027-09-30        2576000.0  ...       2.828928e+06  0.111251
31  2027-12-31        2576000.0  ...       2.836447e+06  0.111162
32  2028-03-31        2576000.0  ...       2.844005e+06  0.111473
33  2028-06-30        1568000.0  ...       1.719898e+06  0.111369
34  2028-09-30        1568000.0  ...       1.724498e+06  0.111319
35  2028-12-31        1568000.0  ...       1.729120e+06  0.111272
36  2029-03-31        1568000.0  ...       1.733766e+06  0.111226
37  2029-06-30        1568000.0  ...       1.738434e+06  0.111699

[38 rows x 7 columns]